### ISSUE TITLE
Cannot pass protocol to CarbonClient

### ISSUE THREAD

**Issue by panzi** [raffaelecalza/monoxide.js#3]
The README claims you can pass the protocol as the second argument to the CarbonClient class constructor, but that constructor only takes one argument. See:
https://github.com/raffaelecalza/monoxide.js/blob/d6a3069a2a567ba03d5e0dd1d99ee14a5b6a47d3/lib/clients/carbon_client.js#L6

**Comment by raffaelecalza** [comment]
@panzi you're right, I didn't saw this problem because I always tested the library with the plaintext protocol. I'll fix this in the next few days. Thanks 👍

**Comment by raffaelecalza** [comment]
I fixed the problem. Now the protocol that CarbonClient object use is the object that you pass to the constructor
